### ISSUE TITLE
demo run dev:wechat 报错，Cannot read property 'selector' of undefined

### ISSUE THREAD

**Issue by goldlin** [kaola-fed/megalo-demo#14]
看着像是 todomvc 的样式里用了什么less不支持的语法导致seletor解析异常？
删掉todomvc就编译通过了

npm 6.5.0
mini-css-extract-plugin@0.4.5
@megalo/target@0.5.8
```
├─┬ @megalo/target@0.5.8
│ ├─┬ @vue/component-compiler-utils@2.5.0
│ │ └── postcss-selector-parser@5.0.0  deduped
│ └── postcss-selector-parser@5.0.0
└─┬ optimize-css-assets-webpack-plugin@5.0.1
  └─┬ cssnano@4.1.8
    └─┬ cssnano-preset-default@4.0.6
      ├─┬ postcss-calc@7.0.1
      │ └── postcss-selector-parser@5.0.0  deduped
      ├─┬ postcss-merge-longhand@4.0.10
      │ └─┬ stylehacks@4.0.1
      │   └── postcss-selector-parser@3.1.1
      ├─┬ postcss-merge-rules@4.0.2
      │ └── postcss-selector-parser@3.1.1
      └─┬ postcss-minify-selectors@4.0.1
        └── postcss-selector-parser@3.1.1
```
```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@megalo/target/lib/frameworks/vue/loader/style.js):
TypeError: Cannot read property 'selector' of undefined
    at new Parser (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss-selector-parser/dist/parser.js:158:74)
    at Processor._root (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss-selector-parser/dist/processor.js:47:22)
    at Processor._runSync (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss-selector-parser/dist/processor.js:83:25)
    at Processor.processSync (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss-selector-parser/dist/processor.js:177:27)
    at root.each.r (/Users/goldlin/GitHub/megalo-demo/node_modules/@megalo/target/lib/postcss-plugins/tag-selector-transform.js:19:13)
    at Root.each (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss/lib/container.js:101:16)
    at /Users/goldlin/GitHub/megalo-demo/node_modules/@megalo/target/lib/postcss-plugins/tag-selector-transform.js:10:10
    at LazyResult.run (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.sync (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss/lib/lazy-result.js:281:26)
    at LazyResult.stringify (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss/lib/lazy-result.js:305:10)
    at LazyResult.get (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss/lib/lazy-result.js:350:19)
    at doCompileStyle (/Users/goldlin/GitHub/megalo-demo/node_modules/@vue/component-compiler-utils/dist/compileStyle.js:60:23)
    at compileStyle (/Users/goldlin/GitHub/megalo-demo/node_modules/@vue/component-compiler-utils/dist/compileStyle.js:8:12)
    at Object.module.exports (/Users/goldlin/GitHub/megalo-demo/node_modules/@megalo/target/lib/frameworks/vue/loader/style.js:20:33)
    at runLoaders (/Users/goldlin/GitHub/megalo-demo/node_modules/webpack/lib/NormalModule.js:301:20)
    at /Users/goldlin/GitHub/megalo-demo/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/goldlin/GitHub/megalo-demo/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at Object.context.callback (/Users/goldlin/GitHub/megalo-demo/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.module.exports (/Users/goldlin/GitHub/megalo-demo/node_modules/@megalo/target/lib/frameworks/vue/loader/style.js:31:10)

 @ ./src/pages/todomvc/index.vue?vue&type=style&index=0&lang=less& 1:0-353 1:369-372 1:374-724 1:374-724
 @ ./node_modules/vue-loader/lib??vue-loader-options!./node_modules/eslint-loader??ref--7-0!./src/pages/todomvc/index.vue
 @ ./src/pages/todomvc/index.vue

 error  in ./src/packageA/pages/todomvc/TodoMVC.vue?vue&type=style&index=0&lang=less&

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@megalo/target/lib/frameworks/vue/loader/style.js):
TypeError: Cannot read property 'selector' of undefined
    at new Parser (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss-selector-parser/dist/parser.js:158:74)
    at Processor._root (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss-selector-parser/dist/processor.js:47:22)
    at Processor._runSync (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss-selector-parser/dist/processor.js:83:25)
    at Processor.processSync (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss-selector-parser/dist/processor.js:177:27)
    at root.each.r (/Users/goldlin/GitHub/megalo-demo/node_modules/@megalo/target/lib/postcss-plugins/tag-selector-transform.js:19:13)
    at Root.each (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss/lib/container.js:101:16)
    at /Users/goldlin/GitHub/megalo-demo/node_modules/@megalo/target/lib/postcss-plugins/tag-selector-transform.js:10:10
    at LazyResult.run (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.sync (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss/lib/lazy-result.js:281:26)
    at LazyResult.stringify (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss/lib/lazy-result.js:305:10)
    at LazyResult.get (/Users/goldlin/GitHub/megalo-demo/node_modules/postcss/lib/lazy-result.js:350:19)
    at doCompileStyle (/Users/goldlin/GitHub/megalo-demo/node_modules/@vue/component-compiler-utils/dist/compileStyle.js:60:23)
    at compileStyle (/Users/goldlin/GitHub/megalo-demo/node_modules/@vue/component-compiler-utils/dist/compileStyle.js:8:12)
    at Object.module.exports (/Users/goldlin/GitHub/megalo-demo/node_modules/@megalo/target/lib/frameworks/vue/loader/style.js:20:33)
    at runLoaders (/Users/goldlin/GitHub/megalo-demo/node_modules/webpack/lib/NormalModule.js:301:20)
    at /Users/goldlin/GitHub/megalo-demo/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/goldlin/GitHub/megalo-demo/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at Object.context.callback (/Users/goldlin/GitHub/megalo-demo/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.module.exports (/Users/goldlin/GitHub/megalo-demo/node_modules/@megalo/target/lib/frameworks/vue/loader/style.js:31:10)

 @ ./src/packageA/pages/todomvc/TodoMVC.vue?vue&type=style&index=0&lang=less& 1:0-370 1:386-389 1:391-758 1:391-758
 @ ./node_modules/vue-loader/lib??vue-loader-options!./node_modules/eslint-loader??ref--7-0!./src/packageA/pages/todomvc/TodoMVC.vue
 @ ./src/packageA/pages/todomvc/TodoMVC.vue
```

**Comment by bigmeow** [comment]
@goldlin  你可以暂时先把package.json的版本号锁死来解决`"@megalo/target": "0.5.6",`
也可以把TodoMVC.vue里面的引用字体文件的部分注释掉。
0.5.6后的版本都出现了这个问题，应该是个bug
@fengzilong   @elcarim5efil

**Comment by fengzilong** [comment]
升级下

@megalo/target 0.6.2
@megalo/template-compiler@0.7.3
megalo@0.7.3

**Comment by goldlin** [comment]
work well after update to @megalo/target 0.6.2

**Comment by zzzzzshPig** [comment]
我也遇到这个问题，有点坑啊-=-，都要给megalo的target折磨死了
